apiVersion: v1
kind: Service
metadata:
  name: 3drepo
  labels:
    app: 3drepo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: 3drepo
