apiVersion: v1
kind: Service
metadata:
  name: bimcollab
  labels:
    app: bimcollab
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: bimcollab
