apiVersion: v1
kind: Service
metadata:
  name: bcfier
  labels:
    app: bcfier
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: bcfier
