apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: bimserver
  name: bimserver-controller
spec:
  replicas: 1
  selector:
    app: bimserver
  template:
    metadata:
      name: bimserver
      labels:
        app: bimserver
    spec:
      containers:
      - name: bimserver
        image: jenca/docker-bimserver:1.4.0-FINAL-2015-11-04
        env:
        - name: TOMCAT_USER
          value: XXX
        - name: TOMCAT_PASSWORD
          value: XXX
        ports:
        - containerPort: 8080
        
