apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: limesurvey
  name: limesurvey-controller
spec:
  replicas: 1
  selector:
    app: limesurvey
  template:
    metadata:
      name: limesurvey
      labels:
        app: limesurvey
    spec:
      containers:
      - name: limesurvey
        image: crramirez/limesurvey
        ports:
        - containerPort: 80
        