apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rocketchat
  name: rocketchat-controller
spec:
  replicas: 1
  selector:
    app: rocketchat
  template:
    metadata:
      name: rocketchat
      labels:
        app: rocketchat
    spec:
      containers:
      - name: rocketchat
        image: rocketchat
        ports:
        - containerPort: 80
        