apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: bimaas
  name: bimaas-controller
spec:
  replicas: 1
  selector:
    app: bimaas
  template:
    metadata:
      name: bimaas
      labels:
        app: bimaas
    spec:
      containers:
      - name: bimaas
        image: bimaas
        ports:
        - containerPort: 8080
        