apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: redmine
