apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: flarum
  name: flarum-controller
spec:
  replicas: 1
  selector:
    app: flarum
  template:
    metadata:
      name: flarum
      labels:
        app: flarum
    spec:
      containers:
      - name: flarum
        image: sebp/flarum
        ports:
        - containerPort: 80
        